/** @type {import('next').NextConfig} */
const nextConfig = {
    async redirects() {
      return [
        {
          source: '/',
          destination: '/pages/tables',
          permanent: false,
          
        },
      ];
    },
    async headers() {
      return [
        {
          source: '/',
          headers: [
            {
              key: 'title',
              value: 'Create Next App',
            },
            {
              key: 'description',
              value: 'Generated by create next app',
            },
          ],
        },
      ];
    },
  };
  
  export default nextConfig;
  